### ISSUE TITLE
Custom merging on GroupBy

### ISSUE THREAD

**Issue by georeith** [omnidan/redux-undo#263] opened 2020-02-12 11:53 UTC
#### I'm submitting a ...
  - [ ] Bug report
  - [x] Feature request
  - [ ] Docs update
  - [ ] Support request => Please do not submit support requests here, see note at the top of this template.

#### What is the current behavior/state of the project?

GroupBy replaces the last state in the timeline with my new state.

#### What is the desired behavior?

Take an optional merge function which takes the old state, the new state and returns the state that groupBy should store.

#### If this is a feature request, what is the use case for changing the behavior?

There may be parts of state that are not absolute. E.g., in my case I store a JSON diff of the change applied by the last action under a property `lastChange`. This `lastChange` property gets overwritten when I group two states in undo when I would like to concatenate the fields together instead.

This way I am able to persist my actions to the server and it is able to redo. You may be asking why I use redux-undo if I have JSON patches, it is because there is some additional UI information (current selection) that I want to undo / redo during the lifetime of a client's session but not persist to server.

This allows me to keep my grouping and filtering logic in redux-undo but maintain a correct list of changes against each point of history.

#### Please tell us about your environment:
  
  - Library version: 1.0.0-beta9-9-7
  - Redux version: 4.0.1
  - Browser: all
  - Language: ES6/7 | ES5

#### Other information

I am happy to take a stab at implementing this I just wanted to see if you saw any potential pitfalls or were interested in this.

**Comment by nmay231** [comment] 2020-02-12 21:33
This is more complex than it appears at first glance. The issue is that you need to give the merging function all of the *intermediate* states in each grouping. Currently, redux-undo just "forgets" about them. There are two ways to go about solving this specific problem.

1. Either undoable would have to keep track of all the intermediate states in the same group and then pass them as an array when the group changes. This would involve adding yet another field to the state tree like `latestUnmergedStates` or something.

2. Or it could partially merge the states one at a time similar to `array.reduce` but the merge function runs whenever each action is dispatched. This would also need its own field to store it somewhere.

Neither solutions are simple because there are edge cases throughout the `undoable` wrapper that would have to be handled. Because of the implementation complexity and the "niche-ness" of the problem, I don't know if it would be worth adding this as a core feature atm. There is also the performance cost that the general user of this library would have to deal with. However, there may be a more general need if this would integrate with both `groupBy` and `filter`.

- What you could do to solve your problem is to not trust the persisted state and just recreate the JSON diffs whenever you load the persisted data.

- Either that or have a seperate field (`mergedChanges` or something) that keeps track of all merged changes for the current grouping similar to option 2 above.

Let me know if that solves your problem :+1:

**Comment by georeith** [comment] 2020-02-13 16:21
@nmay231 thanks for your response. I'm not sure I understand what you mean by:
> all of the intermediate states in each grouping

In my case I managed to solve it:
```js
const timelineReducer = undoable(
  combineReducers({
    design: designReducer,
    selection: selectionReducer,
  }),
  {
    filter,
    groupBy,
    initTypes: [designActionTypes.DESIGN_IMPORT],
  }
);
const combinedReducer = combineReducers({
  timeline: (state, action, ...args) => {
    const result = timelineReducer(state, action, ...args);
    const filtered = !filter(action, result, state);
    const group = groupBy(action, result, state);
    if (!filtered && group != null && group === state.group) {
      return {
        ...result,
        present: {
          ...result.present,
          design: {
            ...result.present.design,
            lastChange: {
              ...result.present.design.lastChange,
              patches: squash(
                [
                  ...state.present.design.lastChange.patches,
                  ...result.present.design.lastChange.patches,
                ]
              ),
              inversePatches: squash(
                [
                  ...result.present.design.lastChange.inversePatches,
                  ...state.present.design.lastChange.inversePatches,
                ]
              ),
            },
          },
        },
      };
    }
    return result;
  },
  view: viewReducer,
});
```
Isn't this equivalent of changing https://github.com/omnidan/redux-undo/blob/4ae60bb539581b5ce71ad6ba6345fc2395a73083/src/reducer.js#L243
to 
```js
typeof merge === 'function' ? merge(history, res) : res
```

Where do the intermediate states come from?

**Comment by nmay231** [comment] 2020-02-17 09:18
This still seems like the user should control this themselves. This is probably not something we're going to add.

When I finish working on field extensions, you might be able to write it a little more succinctly than you are now. Field extensions are like a hook for undoable that gets the final say for what goes into state. They'll also allow for things like the much requested flattenState feature.

Cheers :+1:

**Closed by nmay231** 2020-02-17 09:18 UTC
