### ISSUE TITLE
Feature: new release

### ISSUE THREAD

**Issue by dbkaplun** [omnidan/redux-undo#197] opened 2018-02-20 17:10 UTC
It would be great to have a new npm release. As it stands, the npm version does not even have `groupBy`.

Thanks for considering!

**Comment by tommedema** [comment] 2018-05-15 06:08
@omnidan any chance this can be done? cheers

**Comment by martinAnsty** [comment] 2018-05-26 16:19
The current beta release (9-9-7) is available on npm with `redux-undo@beta`, should be up to date with master (including `groupBy`).

If you're just asking about a stable release, sure, it'd be good to know what needs to be worked on before this version could be considered for a stable release.

**Comment by omnidan** [comment] 2018-07-02 19:32
@martinAnsty there are a lot of things that need to be worked on, like async actions, performance problems, etc. The main issue is that I do not have time or motivation for this project anymore (I do not use it myself at the moment) and nobody else is actively maintaining it right now.

If anyone would be interested in helping maintain the library, that would be awesome. just hop on gitter and we can discuss the future of the library together there: https://gitter.im/omnidan/redux-undo

**Comment by omnidan** [comment] 2018-07-05 08:42
duplicate of #148

**Closed by omnidan** 2018-07-05 08:42 UTC
