### ISSUE TITLE
Bump version?

### ISSUE THREAD

**Issue by pavsidhu** [omnidan/redux-undo#240] opened 2019-09-11 15:40 UTC
There's a lot of changes in this repo that are not available unless add the actual git repo as a dependancy. Is a new release possible?

**Comment by cdietschrun** [comment] 2019-10-10 21:25
npm install redux-undo@beta

**Comment by nmay231** [comment] 2019-12-14 06:40
Duplicate of #148.

I'm currently working on documentation so we can publish the latest version.

**Closed by nmay231** 2019-12-14 06:40 UTC
