### ISSUE TITLE
Action is not applied if state created

### ISSUE THREAD

**Issue by iofjuupasli** [omnidan/redux-undo#268] opened 2020-03-22 09:51 UTC
https://github.com/omnidan/redux-undo/blob/931b2ecda73cfcf91a336d3ccffee1e744eb4483/src/reducer.js#L119-L130

I use state with different history for each key:
```ts
type ItemsStateWithHistory = {
    [key: string]: StateWithHistory<Array<Item>>;
};
```

So if I try to apply action:
```ts
const action = {type: `MY_ACTION`};
return {
  ...state,
  [key]: itemsReducer(substate, action),
};
```

the `MY_ACTION` is not applied to the state.

Only `@@redux-undo/CREATE_HISTORY` is used, and `MY_ACTION` just ignored

**Comment by iofjuupasli** [comment] 2020-03-22 16:35
And another issue with my approach:
https://github.com/omnidan/redux-undo/blob/931b2ecda73cfcf91a336d3ccffee1e744eb4483/src/reducer.js#L111

reducer wrapper is stateful, so when I create substate for another `key`, it initialized with `initialState` of another `key`.

**Comment by iofjuupasli** [comment] 2020-03-22 16:38
My workaround is:

```ts
            const itemsReducerWithHistory = undoable(
                itemsReducer,
                undoableConfig,
            );
            const keyData =
                state[key] ||
                itemsReducerWithHistory(undefined, { type: `@@INIT` });
            return {
                ...state,
                [key]: itemsReducerWithHistory(keyData, action),
            };
```

So, reducer created on every action handling, so `initialState` is empty. And first it initialized with `@@INIT` action (that's ignored in my own reducer, but "history init" action triggered, so state can be initialized)

**Comment by nmay231** [comment] 2020-03-23 04:35
Simply put, this is what is expected. Redux-undo's `undoable()` treats the initial action, regardless of what it is, as an init action passing it the initialState. This works for most use-cases.

I would suggest keeping the same undoable reducer for all your substates. Maybe store it in a closure? For example.

```js
const closure = () => {
  // Define it once
  let undoableReducer = undoable(itemsReducer, config)
  // Initialize the reducer with whatever inital state you want
  const initialState = undoableReducer(undefined, {type: 'doesnt matter'})

  return (state, action) => {
    switch (action.type) {
      case 'ACTION_TYPE':
        return { ...state, [key]: undoableReducer(state[key] || initalState, action) }
    }
  }
}

export const mainReducer = closure()
```

Alternatively (if you need the initial state to be separate for each slice), you can create an object that stores a function for each slice of state replacing every `undoableReducer( ... )` with `reducers[key]( ... )`. That does mean you'll have to initialize every new slice similar to what you have been doing.

```js
if (state[key]) {
  const keyData = state[key]
} else {
  reducers[key] = undoable(itemsReducer, config)
  const keyData = undoableReducer(undefined, {type: 'INIT'})
}

return { ...state, [key]: reducers[key](keyData, action) }
```

You can use one of those methods or your current one, whichever works best for you.

Let me know if that clarifies the issue :+1:

**Comment by iofjuupasli** [comment] 2020-03-23 16:59
I think the reducers object will work for my case. And my workaround works too.

> Redux-undo's undoable() treats the initial action, regardless of what it is, as an init action passing it the initialState.

What prevents passing user action? If it's `@@INIT`, then it'll be usually ignored by a reducer. If it's some useful action like in my case - it shouldn't be ignored.

About `initialState` in `undoable` - it's used twice, as a state to set on `init` action, and as a default state of `undoable` reducer in case it's `undefined`.

What for `initialState` is used as a default state?

https://github.com/omnidan/redux-undo/blob/931b2ecda73cfcf91a336d3ccffee1e744eb4483/src/reducer.js#L112

I just can't come up with a case in which it can be used

**Comment by nmay231** [comment] 2020-03-23 19:26
The reducer was designed to assume the first state passed to it is the inital state. Again, that works for most use-cases. It has already been discussed and, yes, undoable is not a pure reducer. There doesn't seem a way to get the initial state in a normal pure way.

The use of `initialState` is that you dispatch an action and reset the state back to the beginning state.
https://github.com/omnidan/redux-undo/blob/931b2ecda73cfcf91a336d3ccffee1e744eb4483/src/reducer.js#L202-L206

Though now that you mention it, the `state = initialState` on line 112 is useless since `initalState` is undefined at that time, making it no better than `state = undefined`.

I'm going to close this issue since it seems there is no bug. If you have further questions, just @- me :+1:

**Closed by nmay231** 2020-03-23 19:26 UTC
Labels: wontfix
